### PR TITLE
Add NuGet Link To The Page

### PR DESCRIPTION
**Pull request by GGJason**
For the beginners, it is hard to find the NuGet package. So, I add the link to README

### CODE REVIEW

**Comment by yojagad** [comment]
Hello, apologies for the delay. Thank you for the contribution! Could you rebase and update this PR so that we can merge this ?

**Comment by yojagad** [comment]
@GGJason Feel free to ping me here once you're done rebasing and I can review it.

**Comment by GGJason** [comment]
Hi @yojagad ,
I have done rebasing, but I am not sure that if I did it correctly

**Comment by yojagad** [comment]
Doesn't look like it unfortunately :(. It might be easier to close and open a new PR after ensuring your fork matches the current dev?

**Comment by GGJason** [comment]
Ok

**Pull request closed without merging**
